NetherFix:

#author @Halq

#Nether roof cord Y
Y: 126

#Teleport player
Teleport: true

#banish player after trying to climb into nether roof
Ban: false

#kick player after trying to climb into nether roof
Kick: false

#Play sound after player trying to climb into nether roof
Sound: true

#chat alert
Alert: true

#Cmd log
Log: true

#Kill Player
Kill: false

#this remove player for vehicle
AntiVeihicleBypass: true



